### ISSUE TITLE
Only white page loading

### ISSUE THREAD

**Issue by RodneyMcKay715** [TheGuywithTheHat/shawzin#2]
After building and running the shawzin web interface i am greeted with a white page in all browsers. Firefox has this issue: 
![grafik](https://user-images.githubusercontent.com/26826816/64075739-788dfd00-ccbc-11e9-83d5-9d8f6d1565a2.png)

![grafik](https://user-images.githubusercontent.com/26826816/64075745-893e7300-ccbc-11e9-8cc8-7e9494ad94ce.png)

What did i do wrong?
The page loads and says "Compozin' " in the title but thats all.
Thanks in advance.

**Comment by TheGuywithTheHat** [comment]
Thanks for the report! Looks like regex lookbehinds are not supported in most browsers other than chrome. Should be an easy fix.
