### ISSUE TITLE
Yo scale conflicting?

### ISSUE THREAD

**Issue by cyanmagentayellow** [TheGuywithTheHat/shawzin#4]
Some old strings are invalid after the Yo scale update

**Comment by TheGuywithTheHat** [comment]
Do you have more details on this, or did it turn out that this isn't an issue any more?

**Comment by TheGuywithTheHat** [comment]
I just added the Yo scale btw

**Comment by cyanmagentayellow** [comment]
Ah, before the Yo scale, you said adding 2 or more notes in a column wouldn't work but I tried and somehow it always worked for me, then after the Yo scale it doesn't work anymore.

**Comment by cyanmagentayellow** [comment]
Btw if you could add the copy/paste it would be really great 💃

**Comment by Kasyrgan1** [comment]
the Update killed the possebility of adding multiple notes on the same string.  0AH 0AO 0AU and so on cant be converted.  ↓→ 1 or  ↓→2 for example. In the Scale it would be (C,F,B,E), (D,G,C,F) and (E,A,D,G) bequse there are all on the same string.

**Comment by TheGuywithTheHat** [comment]
If it worked before, that must have just been luck. I have no validation of special handling implemented for multiple notes on one column, and I'm honestly surprised that that ever worked at all.

What do you mean by copy/paste? You can "paste" songs by clicking the Import song button and then pasting an encoding, and you can "copy" songs by either clicking the Copy to clipboard button or  manually selecting and copying the encoding within the textbox right next to it.

**Comment by cyanmagentayellow** [comment]
> If it worked before, that must have just been luck. I have no validation of special handling implemented for multiple notes on one column, and I'm honestly surprised that that ever worked at all.
> 
> What do you mean by copy/paste? You can "paste" songs by clicking the Import song button and then pasting an encoding, and you can "copy" songs by either clicking the Copy to clipboard button or manually selecting and copying the encoding within the textbox right next to it.

I meant copying notes from 1 column or 1 measure then paste to another
